import React from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, Shield } from 'lucide-react';
import Footer from '../components/Footer';
import Waveform from '../components/Waveform';

export default function TermsOfService() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-ink signal-grid relative overflow-hidden flex flex-col justify-between">
      <div className="blob pointer-events-none absolute left-1/4 top-1/4 w-[400px] h-[400px] bg-gold/8" />
      <div className="blob pointer-events-none absolute right-1/4 bottom-1/4 w-[350px] h-[350px] bg-coral/8" style={{ animationDelay: '-3s' }} />

      <main className="mx-auto w-full max-w-3xl px-6 py-10 flex-grow relative z-10">
        {/* Back Link */}
        <div className="mb-6 animate-fade-up" style={{ opacity: 0 }}>
          <button
            onClick={() => navigate(-1)}
            className="group flex items-center gap-2 text-sm text-slate hover:text-porcelain transition-colors duration-200"
          >
            <ArrowLeft size={16} className="group-hover:-translate-x-1 transition-transform duration-300" /> Back
          </button>
        </div>

        {/* Brand Link */}
        <div className="mb-8 flex items-center gap-2.5 font-display font-bold text-xl text-porcelain animate-fade-up" style={{ opacity: 0, animationDelay: '0.08s' }}>
          <span className="flex h-8 w-8 items-center justify-center rounded-lg bg-white/10 text-gold-soft">
            <Waveform bars={4} className="h-3" />
          </span>
          Podium Legal
        </div>

        {/* Document Header */}
        <div className="mb-10 animate-fade-up" style={{ opacity: 0, animationDelay: '0.16s' }}>
          <span className="inline-flex items-center gap-1 text-[10px] uppercase font-mono tracking-widest text-gold-soft font-semibold mb-2">
            <Shield size={12} /> platform regulations
          </span>
          <h1 className="font-display text-3xl font-bold text-porcelain md:text-4xl">
            Terms of Service
          </h1>
          <p className="mt-2 text-xs font-mono text-slate">
            Last Updated: July 12, 2026
          </p>
        </div>

        {/* Document Body */}
        <div className="bg-ink-soft/80 card-glass rounded-2xl shadow-card-dark p-6 sm:p-8 space-y-6 text-sm text-slate leading-relaxed animate-rise-fade hover:shadow-glow transition-shadow duration-500" style={{ opacity: 0, animationDelay: '0.24s' }}>
          <section className="space-y-2">
            <h3 className="font-display font-semibold text-porcelain text-base">1. Description of Service</h3>
            <p>
              Podium is an AI-powered technical and soft-skill interview rehearsal coaching platform. It enables candidates to upload resumes, generate role-specific mock interview simulations, practice answering questions via audio/text, and receive quantitative and qualitative feedback generated by Google's Gemini AI.
            </p>
          </section>

          <section className="space-y-2">
            <h3 className="font-display font-semibold text-porcelain text-base">2. Account Responsibility</h3>
            <p>
              To use Podium features, you must register a secure account. You are responsible for keeping your password and web token credentials safe, and are liable for all interview generations or resume parsing actions performed under your account.
            </p>
          </section>

          <section className="space-y-2">
            <h3 className="font-display font-semibold text-porcelain text-base">3. AI Feedback & Accuracy</h3>
            <p>
              All feedback, grading, recommendations, strengths, and improvement suggestions are generated programmatically via Google's Gemini AI APIs based on the context of your resume and typed/spoken answers. AI evaluations are intended for preparation purposes only and do not guarantee actual hiring outcomes.
            </p>
          </section>

          <section className="space-y-2">
            <h3 className="font-display font-semibold text-porcelain text-base">4. Acceptable Conduct</h3>
            <p>
              You agree not to upload files containing malware, spoof other candidates' identities, or crawl/exploit the backend interview synthesis endpoints. Excessive automated generations that abuse resources or exceed reasonable limits may lead to immediate profile suspension.
            </p>
          </section>

          <section className="space-y-2">
            <h3 className="font-display font-semibold text-porcelain text-base">5. Liability Disclaimer</h3>
            <p>
              Podium is provided "as-is" without warranty. We are not responsible for resume processing timeouts, voice transcription inaccuracies, speech API failures, or loss of historical mock interview history.
            </p>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  );
}
